from constantes import LANGUAGE

if LANGUAGE == 'fr':
    text = {
    "column1": "ID", 
    "column2": "Marque", 
    "column3": "Ref", 
    "column4": "Nb", 
    "column5": "Prix", 
    "column6": "Date d'achat", 
    "column7": "Argus", 
    "column8": "Date dernier argus", 
    "column9": "Facture", 
    "column10": "Photo", 
    "column11": "Type", 
    "column12": "Numéro de série", 
    "column13": "Commentaire", 
    "column14": "En vente",
    "csv": "Export CSV", 
    "dump": "Sauvegarder BDD",
    "total": "Total",
    "argus_total": "Total argus",
    "mandatory": "* = Infos requises",
    "dialog_type": "Type *",
    "dialog_brand": "Marque *",
    "dialog_ref": "Référence *",
    "dialog_quantity": "Quantité *",
    "dialog_price": "Prix *",
    "dialog_purchase_date": "Date d'achat *",
    "dialog_calendar_close": "Fermer",
    "dialog_argus": "Argus",
    "dialog_argus_date": "Date argus",
    "dialog_invoice": "Facture",
    "dialog_picture": "Photo",
    "dialog_serial": "Numéro de série",
    "dialog_shop": "Toujours en vente",
    "dialog_comment": "Commentaire",
    "dialog_add_button": "Ajouter",
    "dialog_close_button": "Fermer",
    "dialog_update_button": "Modifier",
    "dialog_suppress_title": "CONFIRMATION DE SUPPRESSION",
    "dialog_suppress_yes_button": "oui",
    "dialog_suppress_no_button": "non",
    "notify_suppressed": "supprimé",
    "notify_dialog_miss_mandatory": "Il manque des infos !",
    "notify_dialog_inserted": "enregistré",
    "notify_dialog updated": "mis à jour",
    "logging_add_info": "Ajout de",
    "logging_update_info": "Mise à jour de",
    "logging_update_argus": "Nouvel argus pour ",
    "logging_delete_info": "Suppression de",
    "csv_shop_yes": "oui",
    "csv_shop_no": "non",
    "database_created": "Base de donnée créée avec succès !",
    "database_exists": "La base de donnée existe déjà",
    "database_creation_failed": "La création de la base de donnée a échoué avec l'errueur suivante :",
    "auto_save_ok": "Sauvegarde de la base de donnée réussie !",
    "auto_save_failed": "La sauvegarde de la base de donnée a échouée avec l'erreur suivante :",
    "old_backup_removed": "La sauvegarde datant de 15 ajours a été supprimée",
    "import_data_ok": "Import des données effectué !",
    "import_data_failed": "Import des données échoué avec l'erreur suivante :"
    }
if LANGUAGE == 'eng':
    text = {
    "column1": "ID", 
    "column2": "Brand", 
    "column3": "Ref", 
    "column4": "Quantity", 
    "column5": "Price", 
    "column6": "Purchase date", 
    "column7": "Argus", 
    "column8": "Argus date", 
    "column9": "Invoice", 
    "column10": "Picture", 
    "column11": "Type", 
    "column12": "Serial", 
    "column13": "Comment", 
    "column14": "Available in shop",
    "csv": "CSV file", 
    "dump": "Dump database",
    "total": "Total",
    "argus_total": "Argus total",
    "mandatory": "* = Mandatory",
    "dialog_type": "Type *",
    "dialog_brand": "Brand *",
    "dialog_ref": "Reference *",
    "dialog_quantity": "Quantity *",
    "dialog_price": "Price *",
    "dialog_purchase_date": "Purchase date *",
    "dialog_calendar_close": "Close",
    "dialog_argus": "Argus",
    "dialog_argus_date": "Argus date",
    "dialog_invoice": "Invoice",
    "dialog_picture": "Picture",
    "dialog_serial": "Serial",
    "dialog_shop": "Still avalaible",
    "dialog_comment": "Comment",
    "dialog_add_button": "Add",
    "dialog_close_button": "Close",
    "dialog_update_button": "Update",
    "dialog_suppress_title": "ARE YOU SURE ?",
    "dialog_suppress_yes_button": "yes",
    "dialog_suppress_no_button": "no",
    "notify_suppressed": "removed",
    "notify_dialog_miss_mandatory": "Please fill mandatory inputs !",
    "notify_dialog_inserted": "inserted",
    "notify_dialog updated": "updated",
    "logging_add_info": "Inserted",
    "logging_update_info": "Updated",
    "logging_update_argus": "New argus for ",
    "logging_delete_info": "Removed",
    "csv_shop_yes": "yes",
    "csv_shop_no": "no",
    "database created": "Database created successfully !",
    "database_exists": "Database already exists",
    "database_creation_failed": "Database creation failed with error :",
    "auto_save_ok": "Database saved successfully !",
    "auto_save_failed": "Save database failed with error :",
    "old_backup_removed": "15 days old backup file was removed",
    "import_data_ok": "Data imported successfully !",
    "import_data_failed": "Import failed with error :"
    }